### ISSUE TITLE
browse: sort a-z browse page titles by 'title_sort' instead of 'title'

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-rg#41]
For example. "A Grain of Sand (album)" appears in the A's instead of the G's.

**Comment by gjost** [comment]
One problem: articles in editors' wiki should include a DEFAULTSORT property
```
{{ DEFAULTSORT:AbeSanji }}
```

**Comment by gjost** [comment]
Another problem, the articles list view may not be sorting by the `title_sort` field.

**Comment by GeoffFroh** [comment]
The articles are sorted using a data value that should already exist in the original wikitext, e.g., 
`{{ DEFAULTSORT:GrainofSandA }}`

In some cases, that value does not exist and needs to be added into the article from the editors' mediawiki
