### ISSUE TITLE
search: when results have more than one page, last result on page is empty text

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-rg#53]
for any search that returns multiple pages of results, the last result of each page appears to be an empty item. See:

http://encycrg.local/search/?fulltext=tule+lake

or

http://encycrg.local/search/?fulltext=manzanar

The behavior appears on all pages except the last one.

**Comment by gjost** [comment]
Happens on the browse pages too, which use the same `Search`, `SearchResults`, and template code.

**Comment by gjost** [comment]
Fixed in commit `e7b2a07`.
