### ISSUE TITLE
search: when no values exist for facet in search results, filter is still displayed

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-rg#54]
Will need to figure out how to do the html layout since it assumes a fixed number of facets.

Example: http://encycrg.local/search/?fulltext=yasui

**Comment by gjost** [comment]
IIRC the problem is that the layout code uses table rows so we can't just list the filters with values.  I'll have a look tho.

**Comment by gjost** [comment]
Fixed in commit `e7b2a07`.

**Comment by gjost** [comment]
Oops, closed the wrong issue.

**Comment by GeoffFroh** [comment]
fixed in dc2d367566cf5e5c36905a25edc4dfcadfdfead5
