### ISSUE TITLE
rg_relatedevents and rg_pov should not be analyzed in ES

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-rg#6]
`rg_relatedevents` and `rg_pov` should not be analyzed by ES.
 See: https://github.com/densho/encyc-rg/blob/master/encycrg/rg/models.py#L288 and https://github.com/densho/encyc-rg/blob/master/encycrg/rg/models.py#L287) 

Their attributes should be set as: `index='not_analyzed' ,multi=True`

Note: `rg_pov` is not currently exposed publicly by the API -- that's OK for now.

**Comment by gjost** [comment]
Fixed this in `encyc-rg` and `encyc-core`
