### ISSUE TITLE
Expanded media details not displaying correctly

### ISSUE THREAD

**Issue by sarabeckman** [densho/encyc-rg#72]
The expanded media details for Short Story, Essay, and Article types does not display correctly. 

Example: https://rgstage.densho.org/The%20Shoyu%20Kid%20(short%20story)/
![MediaDetails](https://user-images.githubusercontent.com/38959538/74971316-c1ee1800-53d4-11ea-8be7-18300bcc77a9.PNG)

**Comment by gjost** [comment]
This issue also affects the current production site: https://resourceguide.densho.org/The%20Shoyu%20Kid%20(short%20story)/
Obviously it needs to be fixed but it's not a regression.

**Comment by gjost** [comment]
It doesn't seem to affect all databoxes e.g. http://rgstage.densho.org/The%20Internment%20of%20the%20Japanese%20(book)/

**Comment by GeoffFroh** [comment]
Fixed in daf95506898683eca73fdf4a8bc366ea218f1847

**Comment by gjost** [comment]
Merged in to `encyc-rg` `develop` branch for package ` encycrg-master_3.0.1`.
