### ISSUE TITLE
Miscategorized resources 

### ISSUE THREAD

**Issue by sarabeckman** [densho/encyc-rg#73]
Two resources miscategorized as Films instead of Films & Videos in the Media Type designation. Clicking on Film leads to a 500 page on rgstage. 

In Interest Level - a miscategorization as 9-12 instead of Grades 9-12. High school instead of High School.  Clicking on the bad categories does NOT result in a 500 page.
 
In Availability - Widely Available instead of Widely available Clicking on the bad categories does NOT result in a 500 page.

**Comment by GeoffFroh** [comment]
Fixed incorrectly tagged film articles

**Comment by GeoffFroh** [comment]
Fixed incorrectly tagged interest level

**Comment by GeoffFroh** [comment]
Fixed incorrectly tagged availability

**Comment by gjost** [comment]
Ran `encyc-core articles` which published the changes @GeoffFroh made in the editors wiki.
