### ISSUE TITLE
Need to add ui support for "Curricula" media type

### ISSUE THREAD

**Issue by GeoffFroh** [densho/encyc-rg#74]
There is currently no support for "Curricula" media type articles. Articles tagged with media type `curricula` can be displayed, but lack an icon and are not browsable from browse-by-media-type page. 

- [x] `templatetags/rg_tags.py`: need to edit types ln 61

related to #73

**Comment by GeoffFroh** [comment]
Turns out that the only necessary change was in the media types in models.py

**Comment by GeoffFroh** [comment]
Fixed in 5f7ca3558a1b0fccaf457d6640877d391b8b3e26

**Comment by gjost** [comment]
Merged in to `encyc-rg` `develop` branch for `package encycrg-master_3.0.1`.
